# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170406_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='member',
            new_name='name',
        ),
    ]
